function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed

	local position = go.get_position()
	for i = 0, 2 do
		local y = position.y - (i * 185)
		for j = 0, 2 do
			local x = position.x + (j * 185)
			local box_pos = vmath.vector3(x, y, 0)
			factory.create("#box_factory", box_pos, nil, {x_pos = i + 1, y_pos = j + 1})
		end
	end
end
